### ISSUE TITLE
Is the ActiveAuthentication implementation correct?

### ISSUE THREAD

**Issue by rubenstolk** [eVRMTV/eVR#2]
https://github.com/eVRMTV/eVR/blob/bb4546340cfc2a56f6da46b9aee50f225834c69d/src/eVR.Reader/ElementaryFiles/EFAA.cs#L107

I'm not getting true for ActiveAuthentication... Am I missing something?

**Comment by rubenstolk** [comment]
Turns out this is the issue:

https://github.com/eVRMTV/eVR/blob/master/src/eVR.Reader/ElementaryFiles/EFAA.cs#L72

First, `RND` is being created, then a different RandomArray is being sent in the `internalAuthent`...

**Comment by eVRMTV** [comment]
Resolved in release 2.0.0.0.
